ofver scripts for pypelib update

diff --git a/vt_manager/bin/versions/default/install/lib/dependencies b/vt_manager/bin/versions/default/install/lib/dependencies
--- a/vt_manager/bin/versions/default/install/lib/dependencies
+++ b/vt_manager/bin/versions/default/install/lib/dependencies
@@ -23,17 +23,26 @@ if [[ ! -d /usr/lib/python2.6 ]]; then
     fi
 fi
 
-# Installing pyPElib (only if not previously installed)
-installedPypelib=`dpkg --get-selections | grep "pypelib" | grep "install"`
-if [[ $installedPypelib == "" ]]; then
+# Installing pyPElib (if not previously installed or version not up to date)
+pypelibUpToDate=`dpkg --get-selections | grep "pypelib" | grep "install"`
+# 1st: install check
+if [[ $pypelibUpToDate != "" ]]; then
+    pypelibCurrentVersion=`sudo dpkg --list pypelib | awk '{for (i=1;i<=NF;i++) if (i==3) { print $i } }' | tail -n 1`
+    sudo /usr/bin/wget https://pypelib.googlecode.com/git/VERSION -O pypelib.version.tmp || error "Could not check pypelib latest version. Do you have connectivity?"
+    pypelibLatestVersion=`cat pypelib.version.tmp`
+    rm pypelib.version.tmp || error "Could not remove pypelib.version.tmp"
+    if [[ $pypelibCurrentVersion != $pypelibLatestVersion ]]; then
+       $pypelibUpToDate=""
+    fi
+fi
+# 2nd: up-to-date check
+if [[ $pypelibUpToDate == "" ]]; then
     print "Downloading latest pypelib version..."
     /usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
-
     print "Installing pypelib_latest_all.deb..."
     /usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
-
     print "Removing temporary files..."
-    rm pypelib_latest_all.deb || "Could not remove pypelib_latest_all.deb"
+    rm pypelib_latest_all.deb || error "Could not remove pypelib_latest_all.deb"
 fi
 
 # Checks that Python's mod_wsgi is enabled in the Apache's mod-enabled folder
