Issue #29: Move LDAP settings to a more configurable location, and stop tracking them in the repository. Plus Dashboard link at logo on every GUI

diff --git a/vt_manager/bin/versions/default/install/lib/dependencies b/vt_manager/bin/versions/default/install/lib/dependencies
--- a/vt_manager/bin/versions/default/install/lib/dependencies
+++ b/vt_manager/bin/versions/default/install/lib/dependencies
@@ -6,16 +6,32 @@ DEBIAN_DEPENDENCIES="apache2 openssl ssl-cert libapache2-mod-wsgi libapache2-mod
 
 EASY_INSTALL_DEPENDENCIES="django-evolution django-autoslug"
 
-#Installing pyPElib
+# Checks that Python 2.6 exists or points to current version for pyPElib
+if [[ ! -d /usr/lib/python2.6 ]]; then
+    pyVersion="python"`python -c "import sys; print(sys.version.split(' ')[0])"`
+    i=3
+    while [[ ! -d /usr/lib/$pyVersion && $i -gt 0 ]]; do
+        # Looks for the 'longest' version possible
+        case $i in
+            2) pyVersion="python$(expr "$pyVersion" : 'python\([0-9].[0-9]\).*')" ;;
+            1) pyVersion="python$(expr "$pyVersion" : 'python\([0-9]\).*')" ;;
+        esac
+        i=$((i-1))
+    done
+    if [[ -d /usr/lib/$pyVersion ]]; then
+        ln -s /usr/lib/$pyVersion /usr/lib/python2.6
+    fi
+fi
 
-print "Downloading latest pypelib version..."
-/usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
+# Installing pyPElib (only if not previously installed)
+installedPypelib=`dpkg --get-selections | grep "pypelib" | grep "install"`
+if [[ $installedPypelib == "" ]]; then
+    print "Downloading latest pypelib version..."
+    /usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
 
-print "Installing pypelib_latest_all.deb..."
-/usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
+    print "Installing pypelib_latest_all.deb..."
+    /usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
 
-print "Removing temporary files..."
-rm pypelib_latest_all.deb || "Could not remove pypelib_latest_all.deb"
-
-
-
+    print "Removing temporary files..."
+    rm pypelib_latest_all.deb || "Could not remove pypelib_latest_all.deb"
+fi
