TemplateDownloader: do not ask twice for type of installation (II)

diff --git a/vt_manager/src/python/agent/tools/versions/default/install/install b/vt_manager/src/python/agent/tools/versions/default/install/install
--- a/vt_manager/src/python/agent/tools/versions/default/install/install
+++ b/vt_manager/src/python/agent/tools/versions/default/install/install
@@ -41,6 +41,11 @@ source "$CURRENT_DIRECTORY/lib/daemon"
 
 printHeader ">" "Downloading templates..." 
 #source "$CURRENT_DIRECTORY/lib/template"
+# Retrieve type of installation (OFELIA/NON-OFELIA)
+template_arguments=""
+if [[ $OFELIA == 1 ]]; then
+    template_arguments="--ofelia"
+fi
 # Daemon already installed (in previous line)
-/etc/init.d/oxad update-templates || error "Could not update templates" $NO_RESCUE
+/etc/init.d/oxad update-templates $template_arguments || error "Could not update templates" $NO_RESCUE
 
diff --git a/vt_manager/src/python/agent/tools/versions/default/upgrade/default/upgrade b/vt_manager/src/python/agent/tools/versions/default/upgrade/default/upgrade
--- a/vt_manager/src/python/agent/tools/versions/default/upgrade/default/upgrade
+++ b/vt_manager/src/python/agent/tools/versions/default/upgrade/default/upgrade
@@ -17,5 +17,10 @@ printHeader "info#" "Using default upgrade module..."
 print "Checking for new versions of the VM template..."
 #loadModule "lib/template" $NO_RESCUE
 #source "$CURRENT_DIRECTORY/lib/template"
+# Retrieve type of installation (OFELIA/NON-OFELIA)
+template_arguments=""
+if [[ $OFELIA == 1 ]]; then
+    template_arguments="--ofelia"
+fi
 # Daemon already installed
-/etc/init.d/oxad update-templates || error "Could not update templates" $NO_RESCUE
+/etc/init.d/oxad update-templates $template_arguments || error "Could not update templates" $NO_RESCUE
