OFELIA CF release 0.4

diff --git a/vt_manager/bin/versions/default/upgrade/default/pre-upgrade-hook b/vt_manager/bin/versions/default/upgrade/default/pre-upgrade-hook
--- a/vt_manager/bin/versions/default/upgrade/default/pre-upgrade-hook
+++ b/vt_manager/bin/versions/default/upgrade/default/pre-upgrade-hook
@@ -29,3 +29,13 @@ while [ $OFELIA != "yes" ] && [ $OFELIA != "no" ] && [ $OFELIA != 1 ] && [ $OFEL
             echo "Not valid option. Please say yes/no"
         fi
     done
+
+## PyPElib installation ...
+print "Downloading latest pypelib version..."
+/usr/bin/wget http://pypelib.googlecode.com/files/pypelib_latest_all.deb || error "Could not download pypelib latest version from http://pypelib.googlecode.com/files/pypelib_latest_all.deb. Do you have connectivity?"
+
+print "Installing pypelib_latest_all.deb..."
+/usr/bin/dpkg -i pypelib_latest_all.deb || error "Could not install pypelib latest version using /usr/bin/dpkg -i pypelib_latest_all.deb"
+
+print "Removing temporary files..."
+rm pypelib_latest_all.deb || warning "Could not remove pypelib_latest_all.deb"
