Solving small bug in version-checks on upgrade

diff --git a/expedient/bin/versions/version-checks b/expedient/bin/versions/version-checks
--- a/expedient/bin/versions/version-checks
+++ b/expedient/bin/versions/version-checks
@@ -28,16 +28,15 @@ if [ -n "$CURRENT_VERSION" -a  "$ACTION" == "install"  ]; then
 fi
 #Check upgrade 
 if [ "$ACTION" == "upgrade"  ]; then
-	if [ "$FORCE" == 0 ]; then 
-		if [[ "$TARGETED_VERSION" == "$CURRENT_VERSION" ]]; then
+	if [[ "$TARGETED_VERSION" == "$CURRENT_VERSION" ]]; then
+		if [ "$FORCE" == 0 ]; then 
 			error "Cannot upgrade; targeted version is the same as current installed version. Use force if you want to override this..." $NO_RESCUE
+		else
+			confirm "Targeted version and current are the same one. Are you sure you want to force upgrade." $DONT_ABORT $NO_RESCUE
+			if [ $? == 1 ]; then
+				error "Aborted by the user" $NO_RESCUE	
+			fi
 		fi
-	else
-		confirm "Targeted version and current are the same one. Are you sure you want to force upgrade." $DONT_ABORT $NO_RESCUE
-		if [ $? == 1 ]; then
-			error "Aborted by the user" $NO_RESCUE	
-		fi
-
 
 	fi
 fi
