Solved leaked Slot bug

diff --git a/expedient/bin/versions/version-checks b/expedient/bin/versions/version-checks
--- a/expedient/bin/versions/version-checks
+++ b/expedient/bin/versions/version-checks
@@ -13,3 +13,15 @@ if [[ $TARGETED_VERSION == *R* ]] && [ "$FORCE" == "0" ]; then
 	error "Cannot install Release/Release Candidates in production enviornments. Use force mode if you want to test them" $NO_RESCUE
 fi
 
+if [ "$FORCE" == 0 ]; then 
+	if [[ "$TARGETED_VERSION" == "$CURRENT_VERSION" ]]; then
+		error "Cannot upgrade; targeted version is the same as current installed version. Use force if you want to override this..." $NO_RESCUE
+	fi
+else
+	confirm "Targeted version and current are the same one. Are you sure you want to force upgrade." $DONT_ABORT $NO_RESCUE
+	if [ $? == 1 ]; then
+		error "Aborted by the user" $NO_RESCUE	
+	fi
+
+
+fi
diff --git a/vt_manager/src/python/agent/tools/versions/default/install/lib/template b/vt_manager/src/python/agent/tools/versions/default/install/lib/template
--- a/vt_manager/src/python/agent/tools/versions/default/install/lib/template
+++ b/vt_manager/src/python/agent/tools/versions/default/install/lib/template
@@ -2,7 +2,15 @@
 
 function downloadTemplate
 {
-print "Downloading the template..."
+	#Mkdir
+	mkdir -p $OXA_DIRECTORY/cache/templates/default
+	echo ""	
+	echo "OK of everything is correct, this  may take a while (approx. 1.2GB)..."
+	/usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/default.tar.gz  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.tar.gz || ( rm $OXA_DIRECTORY/cache/templates/default/default.tar.gz && error "Cannot download template from storage system!!!" )
+}
+
+
+print "VM template installation..."
 
 
 	echo "Please enter the USERNAME for the OFELIA storage system to download the default template. Credentials are the same ones used in Ofelia's TRAC, WIKI and SVN (email). Usernames and passwords will NOT be stored."
@@ -14,29 +22,24 @@ print "Downloading the template..."
 	/bin/stty -echo
 	read PASSWORD 
 	/bin/stty echo
-	
-	
-	#Mkdir
-	mkdir -p $OXA_DIRECTORY/cache/templates/default
-	echo ""	
-	echo "OK of everything is correct, this  may take a while (approx. 1.2GB)..."
-	/usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/default.tar.gz  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.tar.gz || ( rm $OXA_DIRECTORY/cache/templates/default/default.tar.gz && error "Cannot download template from storage system!!!" )
-}
 
-if [ ! -f $OXA_DIRECTORY/cache/templates/default/default.tar.gz ];then
-	downloadTemplate	
-else
-	if [ "$FORCE" == 0 ]; then 
-		print ""
-		warning "Default template file already exists; skipping..."
-		print ""
+	echo "Attempting to download HASH file of the template..."	
+	/usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/.default.hash  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.hash || ( rm $OXA_DIRECTORY/cache/templates/default/.default.hash && error "Cannot download HASH for the template from storage system!!!" )
+	if [ ! -f $OXA_DIRECTORY/cache/templates/default/default.tar.gz -o `cat $OXA_DIRECTORY/cache/templates/default/.default.hash` != `cat $OXA_DIRECTORY/cache/templates/default/default.hash`];then
+		downloadTemplate	
 	else
-		confirm "Default template file already exists. Do you want to overwrite it." $DONT_ABORT $NO_RESCUE
+		if [ "$FORCE" == 0 ]; then 
+			print ""
+			warning "Default template file already exists; skipping..."
+			print ""
+		else
+			confirm "Default template file already exists. Do you want to OVERWRITE it (It will not be backuped!)." $DONT_ABORT $NO_RESCUE
 
-		if [ $? == 0 ]; then
-			downloadTemplate	
+			if [ $? == 0 ]; then
+				downloadTemplate	
+			fi
+
 		fi
 
 	fi
-
-fi
+ 	rm -f $OXA_DIRECTORY/cache/templates/default/.default.hash
