Moved settings and rspec plugin into new locations

diff --git a/expedient/bin/versions/default/install/lib/django-settings b/expedient/bin/versions/default/install/lib/django-settings
--- a/expedient/bin/versions/default/install/lib/django-settings
+++ b/expedient/bin/versions/default/install/lib/django-settings
@@ -6,20 +6,20 @@ EDITORS="vi vim emacs nano pico"
 #Copy from template
 printHeader ">" "Copying django settings file from template..."
 
-if [ -f $SRC_DIR/src/python/expedient/clearinghouse/localsettings.py ];then
-	warning "localsettings file already exists."
+if [ -f $SRC_DIR/src/settings/local.py ];then
+	warning "local.py settings file already exists."
 
 	if [ "$FORCE" == "1" ]; then
-		confirm "Overwrite currently installed localsettings.py." $DONT_ABORT
+		confirm "Overwrite currently installed local.py settings file." $DONT_ABORT
 		if [ $? == 0 ]; then			
-			cp $SRC_DIR/src/python/expedient/clearinghouse/localsettings-example $SRC_DIR/src/python/expedient/clearinghouse/localsettings.py -f || error "Cannot copy localsettings.py"
+			cp $SRC_DIR/src/settings/local-example $SRC_DIR/src/settings/local.py -f || error "Cannot copy local.py settings file"
 		fi 
 	else
 		print "Skipping copy (will not be overwritten)"
 	fi
 else
-	print "$SRC_DIR""src/python/expedient/clearinghouse/localsettings-example -> $SRC_DIR""src/python/expedient/clearinghouse/localsettings.py "
-	cp $SRC_DIR/src/python/expedient/clearinghouse/localsettings-example $SRC_DIR/src/python/expedient/clearinghouse/localsettings.py || error "Cannot copy localsettings.py"
+	print "$SRC_DIR""src/settings/local-example -> $SRC_DIR""src/settings/local.py "
+	cp $SRC_DIR/src/settings/local-example $SRC_DIR/src/settings/local.py || error "Cannot copy local.py settings file"
 fi
 
 #Choose editor
@@ -37,15 +37,15 @@ do
 done
 
 #Edit file
-printHeader ">" "Editing localsettings file..."
+printHeader ">" "Editing local.py settings file..."
 while :	
 do
-	print "Now you are going to edit the file $SRC_DIR""src/python/expedient/clearinghouse/localsettings.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
+	print "Now you are going to edit the file $SRC_DIR""src/settings/local.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
 	pause ""
-	eval $EDITOR $SRC_DIR/src/python/expedient/clearinghouse/localsettings.py
+	eval $EDITOR $SRC_DIR/src/settings/local.py
 	print ""
 	pause "Now the contents of the file will be shown for a final review. You can scroll up/down to verify the settings. Press 'q' to continue..."
-	less $SRC_DIR/src/python/expedient/clearinghouse/localsettings.py
+	less $SRC_DIR/src/settings/local.py
 	
 	confirm "Everything is OK." $DONT_ABORT $NO_RESCUE
 
