Adding backup and restore for Expedient

diff --git a/expedient/bin/versions/default/upgrade/default/rollback b/expedient/bin/versions/default/upgrade/default/rollback
--- a/expedient/bin/versions/default/upgrade/default/rollback
+++ b/expedient/bin/versions/default/upgrade/default/rollback
@@ -10,3 +10,25 @@
 #inform user
 printheader "info#" "Using default rollback module..."
 
+
+confirm "It seems something went wrong.. Now you will be able to rollback to the previous state of the filsystem and database. Alternatevily you can try to solve the problem manually, avoiding the rollback mechanism. Do you want to rollback now?" $DONT_ABORT $NO_RESCUE
+
+if [ $? == 0 ]; then
+	print "Please remember that you can find the log of this upgrade operation under log/ folder. Good luck!"
+	exit 1
+fi
+
+
+
+#Restoring files first
+print "Restoring files..."
+cp $BACKUP_PATH/* $SRC_DIR/ -R || error "Could not restore files. Please take into account that previous state including DB state is in $BACKUP_PATH"
+
+#Restoring database
+print "Restoring database..."
+
+$PWD/../tools/sqlRestore.py $BACKUP_PATH/dbdump.sql || error "Could not restore database. Please take into account that previous state including DB state is in $BACKUP_PATH" 
+
+cd $TMP_PATH
+
+
