ofver post_upgrade_hook for Expedient v0.13 v4

diff --git a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
--- a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
+++ b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
@@ -10,9 +10,6 @@
 #inform user
 printHeader "info#" "Using specific 0.12-0.13 post-upgrade-hook module..."
 
-#Call Rebase pointers to solve BUG
-#$EXECPATH/versions/default/upgrade/tools/UpgradeTools.py rebasePointers
-
 SRC_DIR=/opt/ofelia/expedient/
 EMAIL_PATTERNS="EMAIL_ DEFAULT_EMAIL"
 
@@ -23,7 +20,7 @@ cd $SRC_DIR/src/python/expedient/clearinghouse/ || error "Target directory does 
 
 #Adding/Moving new variables to localsettings.py
 printHeader ">" "Adding new settings to localsettings.py ..."
-echo "ISLAND_NAME = \"changeme\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_PASSWORD to localsettngs.py ..."
+echo "ISLAND_NAME = \"changeme\"" >> localsettings.py || error "Could not add ISLAND_NAME to localsettngs.py ..."
 echo "AUTH_LDAP_BIND_PASSWORD = \"changeme\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_PASSWORD to localsettngs.py ..."
 echo "ALLOW_LOCAL_REGISTRATION = False" >> localsettings.py || error "Could not add ALLOW_LOCAL_REGISTRATION to localsettngs.py ..."
 
