ofver fixed

diff --git a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
--- a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
+++ b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
@@ -25,7 +25,7 @@ read ISLAND_NAME
 echo "ISLAND_NAME = \"$ISLAND_NAME\"" >> localsettings.py || error "Could not add ISLAND_NAME to localsettngs.py ..."
 echo "Set LDAP CN to generate DN: "
 read LDAP_CN
-echo "AUTH_LDAP_BIND_DN = \"cn=$LDAP_CN,ou=admins,dc=fp7-ofelia,dc=eu\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_DN to localsettngs.py ..."
+echo "AUTH_LDAP_BIND_DN = \"uid=$LDAP_CN,ou=admins,dc=fp7-ofelia,dc=eu\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_DN to localsettngs.py ..."
 echo "Set LDAP Password: "
 read LDAP_PASSWORD
 echo "AUTH_LDAP_BIND_PASSWORD = \"$LDAP_PASSWORD\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_PASSWORD to localsettngs.py ..."
