v0.13 final

diff --git a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
--- a/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
+++ b/expedient/bin/versions/0.13/upgrade/0.12/pre-backup-upgrade-hook
@@ -30,7 +30,7 @@ echo "Set LDAP Password: "
 read LDAP_PASSWORD
 echo "AUTH_LDAP_BIND_PASSWORD = \"$LDAP_PASSWORD\"" >> localsettings.py || error "Could not add AUTH_LDAP_BIND_PASSWORD to localsettngs.py ..."
 echo "ALLOW_LOCAL_REGISTRATION = False" >> localsettings.py || error "Could not add ALLOW_LOCAL_REGISTRATION to localsettngs.py ..."
-echo -e "#In days\nSLICE_DEFAULT_EXPIRATION_TIME = 7" >> localsettings.py || error "Could not add SLICE_DEFAULT_EXPIRATION_TIME to localsettngs.py ..."
+echo -e "#In days\nSLICE_DEFAULT_EXPIRATION_TIME = 30" >> localsettings.py || error "Could not add SLICE_DEFAULT_EXPIRATION_TIME to localsettngs.py ..."
 echo -e "\n\nYou can change the new settings by editing localsettings.py file"
 
 
