ofver modifications in v0.14.2 script to handle XMLRPC_USER

diff --git a/vt_manager/bin/versions/0.14.2/install/pre-install-hook b/vt_manager/bin/versions/0.14.2/install/pre-install-hook
--- a/vt_manager/bin/versions/0.14.2/install/pre-install-hook
+++ b/vt_manager/bin/versions/0.14.2/install/pre-install-hook
@@ -9,6 +9,8 @@
 
 #Check for OFELIA installation
 OFELIA="none"
+XMLRPC_PASS="nulValue"
+XMLRPC_PASS2="nulValue2"
 
 while [ $OFELIA != "yes" ] && [ $OFELIA != "no" ] && [ $OFELIA != 1 ] && [ $OFELIA != 0 ]
     do
@@ -22,3 +24,28 @@ while [ $OFELIA != "yes" ] && [ $OFELIA != "no" ] && [ $OFELIA != 1 ] && [ $OFEL
             echo "Not valid option. Please say yes/no"
         fi
     done
+
+cd $SRC_DIR/src/python/vt_manager/ || error "Target directory does not exit anymore?¿"
+
+#Adding/Moving new variables to mySettings.py
+printHeader ">" "Adding new settings to mySettings.py ..."
+echo "Plase set username and password to be used by Expedient to call XMLRPC methods.This credentials are new in v0.14.2 and will be used to any ther entity connected to the northbound interface of the VT Manager to authenticate.\username: "
+read XMLRPC_USER
+while [ $XMLRPC_PASS != $XMLRPC_PASS2 ]
+	do
+		echo "password:"
+		stty -echo
+		read XMLRPC_PASS
+		stty echo
+		echo "repeat password:"
+		stty -echo
+		read XMLRPC_PASS2
+		stty echo
+		if [ $XMLRPC_PASS != $XMLRPC_PASS2 ]; then
+	        	echo "Password does not match, please set it again."
+	done
+sed -i "/XMLRPC_USER/d" mySettings.py || error "Could not delete old ISLAND_NAME setting from mySettings.py ..."
+echo "XMLRPC_USER = \"$ISLAND_NAME\"" >> mySettings.py || error "Could not add ISLAND_NAME to mySettings.py ..."
+sed -i "/XMLRPC_PASS/d" mySettings.py || error "Could not delete old XMLRPC_PASS setting from mySettings.py ..."
+echo "XMLRPC_PASS = \"$XMLRPC_PASS\"" >> mySettings.py || error "Could not add XMLRPC_PASS to mySettings.py ..."
+
