Final touches regarding localsettings.py name and backup

diff --git a/ofam/bin/versions/default/install/lib/django-settings b/ofam/bin/versions/default/install/lib/django-settings
--- a/ofam/bin/versions/default/install/lib/django-settings
+++ b/ofam/bin/versions/default/install/lib/django-settings
@@ -6,20 +6,20 @@ EDITORS="vi vim emacs nano pico"
 #Copy from template
 printHeader ">" "Copying django settings file from template..."
 
-if [ -f /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py ];then
+if [ -f $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py ];then
 	warning "Localsettings file already exists."
 
 	if [ "$FORCE" == "1" ]; then
 		confirm "Overwrite currently installed localsettings.py." $DONT_ABORT
 		if [ $? == 0 ]; then			
-			cp /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings-example /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py || error "Cannot copy localsettings.py"
+			cp $SRC_DIR/local/lib/foam/ofeliasettings/localsettings-example $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py || error "Cannot copy localsettings.py"
 		fi 
 	else
 		print "Skipping copy (will not be overwritten)"
 	fi
 else
-	print "/opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings-example -> /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py "
-	cp /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings-example /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py || error "Cannot copy localsettings.py"
+	print "$SRC_DIR/local/lib/foam/ofeliasettings/localsettings-example -> $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py "
+	cp $SRC_DIR/local/lib/foam/ofeliasettings/localsettings-example $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py || error "Cannot copy localsettings.py"
 fi
 
 #Choose editor
@@ -40,12 +40,12 @@ done
 printHeader ">" "Editing localsettings file..."
 while :	
 do
-	print "Now you are going to edit the file /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
+	print "Now you are going to edit the file $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
 	pause ""
-	eval $EDITOR /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py 
+	eval $EDITOR $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py 
 	print ""
 	pause "Now the contents of the file will be shown for a final review. You can scroll up/down to verify the settings. Press 'q' to continue..."
-	less /opt/ofelia/ofam/local/lib/foam/ofeliasettings/localsettings.py
+	less $SRC_DIR/local/lib/foam/ofeliasettings/localsettings.py
 	
 	confirm "Everything is OK." $DONT_ABORT $NO_RESCUE
 
