Refactoring settings

diff --git a/AMsoil/src/vendor/virtrm/agent/tools/versions/default/install/lib/settings b/AMsoil/src/vendor/virtrm/agent/tools/versions/default/install/lib/settings
--- a/AMsoil/src/vendor/virtrm/agent/tools/versions/default/install/lib/settings
+++ b/AMsoil/src/vendor/virtrm/agent/tools/versions/default/install/lib/settings
@@ -6,20 +6,20 @@ EDITORS="vi vim emacs nano pico"
 #Copy from template
 printHeader ">" "Copying settings file from template..."
 
-if [ -f $OXA_DIRECTORY/bin/mySettings.py ];then
-	warning "mySettings.py file already exists."
+if [ -f $OXA_DIRECTORY/bin/settings/local.py ];then
+	warning "local.py file already exists."
 
 	if [ "$FORCE" == "1" ]; then
-		confirm "Overwrite currently installed mySettings.py." $DONT_ABORT
+		confirm "Overwrite currently installed local.py." $DONT_ABORT
 		if [ $? == 0 ]; then			
-			cp $OXA_DIRECTORY/bin/mySettings-example.py $OXA_DIRECTORY/bin/mySettings.py -f || error "Cannot copy mySettings.py"
+			cp $OXA_DIRECTORY/bin/settings/local-example.py $OXA_DIRECTORY/bin/settings/local.py -f || error "Cannot copy local.py"
 		fi 
 	else
 		print "Skipping copy (will not be overwritten)"
 	fi
 else
-	print "$OXA_DIRECTORY/bin/mySettings-example.py -> $OXA_DIRECTORY/bin/mySettings.py "
-	cp $OXA_DIRECTORY/bin/mySettings-example.py $OXA_DIRECTORY/bin/mySettings.py -f || error "Cannot copy mySettings.py"
+	print "$OXA_DIRECTORY/bin/settings/local-example.py -> $OXA_DIRECTORY/bin/settings/local.py "
+	cp $OXA_DIRECTORY/bin/settings/local-example.py $OXA_DIRECTORY/bin/settings/local.py -f || error "Cannot copy local.py"
 fi
 
 #Choose editor
@@ -40,13 +40,13 @@ done
 printHeader ">" "Editing settings..."
 while :	
 do
-	print "Now you are going to edit the file $OXA_DIRECTORY/bin/mySettings.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
+	print "Now you are going to edit the file $OXA_DIRECTORY/bin/settings/local.py using $EDITOR. Save the modifications and do NOT exit using Ctrl+C..."
 	warning "Make sure you uncomment and define a STRONG password for the XMLRPC interface"
 	pause ""
-	eval $EDITOR $OXA_DIRECTORY/bin/mySettings.py
+	eval $EDITOR $OXA_DIRECTORY/bin/settings/local.py
 	print ""
 	pause "Now the contents of the file will be shown for a final review. You can scroll up/down to verify the settings. Press 'q' to continue..."
-	less $OXA_DIRECTORY/bin/mySettings.py
+	less $OXA_DIRECTORY/bin/settings/local.py
 	
 	confirm "Is it correct OK." $DONT_ABORT $NO_RESCUE
 
