Fix for UNALLOWED_VLAN setting

diff --git a/optin_manager/bin/versions/0.3.1/upgrade/default/post-upgrade-hook b/optin_manager/bin/versions/0.3.1/upgrade/default/post-upgrade-hook
--- a/optin_manager/bin/versions/0.3.1/upgrade/default/post-upgrade-hook
+++ b/optin_manager/bin/versions/0.3.1/upgrade/default/post-upgrade-hook
@@ -19,6 +19,6 @@ cd $SRC_DIR/src/python/openflow/optin_manager/
 #Adding/Moving new variables to mySettings.py
 printHeader ">" "Adding new settings to localsettings.py ..."
 sed -i "/UNALLOWED_VLANS/d" localsettings.py || error "Could not delete old THEME setting from localsettings.py ..."
-echo "UNALLOWED_VLANS = \"\"" >> localsettings.py && echo "Check localsettings-example file for more info about how to configure a custom theme for OCF" || error "Could not add UNALLOWED_VLANS to localsettings.py ..."
+echo "UNALLOWED_VLANS = []" >> localsettings.py && echo "Check localsettings-example file for more info about how to configure a custom theme for OCF" || error "Could not add UNALLOWED_VLANS to localsettings.py ..."
 
 cd $SRC_DIR
