fix

diff --git a/vt_manager/src/python/agent/tools/versions/default/install/lib/template b/vt_manager/src/python/agent/tools/versions/default/install/lib/template
--- a/vt_manager/src/python/agent/tools/versions/default/install/lib/template
+++ b/vt_manager/src/python/agent/tools/versions/default/install/lib/template
@@ -1,15 +1,6 @@
 #!/bin/bash
 
 
-function getTemplateLocation
-{
-	if [ $OFELIA == yes ];then
-        	WGET_COMMAND='/usr/bin/wget --progress=bar:force --no-check-certificate --user='$USERNAME' --password='$PASSWORD' --output-document '$OXA_DIRECTORY'/cache/templates/default/default.tar.gz  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.tar.gz'
-	else
-		WGET_COMMAND='/usr/bin/wget --progress=bar:force --no-check-certificate --output-document '$OXA_DIRECTORY'/cache/templates/default/default.tar.gz  http://codebasin.net/storage/images/xen/templates/Debian/0.1/default.tar.gz'
-	fi	
-}
-
 function downloadTemplate
 {
 	echo ""	
@@ -48,8 +39,8 @@ print "VM template installation..."
 	#Mkdir
 	mkdir -p $OXA_DIRECTORY/cache/templates/default
 	
-	echo "Attempting to download HASH file of the template..."	
-	downloadTemplateHash
+	#Attempting to download HASH file of the template..	
+	downloadTemplateHash || error "Cannot download HASH for the template from storage system!!!"
 #	/usr/bin/wget --progress=bar:force --no-check-certificate --user=$USERNAME --password=$PASSWORD --output-document $OXA_DIRECTORY/cache/templates/default/.default.hash  https://alpha.fp7-ofelia.eu/storage/images/xen/templates/Debian/0.1/default.hash || ( rm $OXA_DIRECTORY/cache/templates/default/.default.hash && error "Cannot download HASH for the template from storage system!!!" $NO_RESCUE )
 	
 	local HASH=`cat $OXA_DIRECTORY/cache/templates/default/default.hash > /dev/null 2>&1 `
