recreating symlink to log, on upgrade

diff --git a/ofam/bin/versions/default/upgrade/default/upgrade b/ofam/bin/versions/default/upgrade/default/upgrade
--- a/ofam/bin/versions/default/upgrade/default/upgrade
+++ b/ofam/bin/versions/default/upgrade/default/upgrade
@@ -34,6 +34,9 @@ if [ -f /etc/nginx/sites-enabled/default ]; then
     mv /etc/nginx/sites-enabled/default /etc/nginx/sites-available/$backup_nginx_conf || error "Could not backup default configuration file for '/etc/nginx/sites-enabled/default'"
 fi
 
+#Symlink application folder for error log (so we can access normally)
+ln -s $SRC_DIR/local/log /var/log/apache2/ofam || error "Cannot create symbolic link: /var/log/apache2/ofam -> $SRC_DIR/local/log" $NO_RESCUE
+
 cd $TMP_PATH
 
 #Django settings 
