Integration: ofelia.development + foamintegration: modified upgrade scripts improvement

diff --git a/ofam/bin/versions/default/upgrade/default/upgrade b/ofam/bin/versions/default/upgrade/default/upgrade
--- a/ofam/bin/versions/default/upgrade/default/upgrade
+++ b/ofam/bin/versions/default/upgrade/default/upgrade
@@ -19,5 +19,13 @@ printHeader ">" "Upgrading FOAM to the latest version..."
 cd $SRC_DIR/src
 python install.py
 
+# Nginx's sites-enabled is renamed using the timestamp.
+# This is done in order to avoid conflicts with FOAM config file
+if [ -f /etc/nginx/sites-enabled/default ]; then
+    backup_nginx_conf=/etc/nginx/sites-enabled/default.bak-`date +"%d_%m_%y-%R"`
+    print "Backing nginx config file up: /etc/nginx/sites-enabled/default => $backup_nginx_conf ..."
+    mv /etc/nginx/sites-enabled/default $backup_nginx_conf || error "Could not backup default configuration file for '/etc/nginx/sites-enabled/default'"
+fi
+
 cd $TMP_PATH
 
